name: Auto Pull Request

on:
  push:
    branches:
      - 'feature/*'  # This ensures it triggers only when a push happens on feature/* branches.

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main  # The target branch (where you want to merge the PR to)
          head: feature/add-file  # The branch with the changes
          title: 'Auto PR: Add file.txt'
          body: 'This is an auto-created PR for adding file.txt'
